### ISSUE TITLE
No more banlog.txt?

### ISSUE THREAD

**Issue by SCUR0** [jjxtra/IPBan#41]
Hello,

I very much appreciate the work going into IPBan.

I noticed with the latest version, it removed a feature of the older IPBan.

I don't see a banlog.txt file that I used to use with my scripts for other tasks (updating .htaccess files).

What does IPBan now use to store banned IPs and can I reference this storage method with other scripts?

**Comment by jjxtra** [comment]
The banlog is the firewall rule and hence was removed due to redundancy. I would suggest to just query the firewall to get your ip addresses. If you are on Windows you can do this with netsh advfirewall. If on Linux, you can do it with ipset.

**Comment by SCUR0** [comment]
Thanks! 

I'll have to update the scripts to Get-NetFirewallRule
