### ISSUE TITLE
Question about Windows 2012 R2

### ISSUE THREAD

**Issue by marcwaz** [jjxtra/IPBan#42]
Hello,

My aim is to block NTLM and RDP brut force attack on Windows Server 2012 R2 .

In your presentation you say:
For Windows Server 2008 or equivelant, you should disable NTLM logins and only allow NTLM2 logins. On Windows Server 2008, there is no way to get the ip address of NTLM logins. Use secpol -> local policies -> security options -> network security restrict ntlm incoming ntlm traffic -> deny all accounts.

Could you explain why ? What is the aim ?
If we don't do it, what's happening ? 
Do we decrease the security by doing this ?
Do we have to do this also on Windows Server 2012 R2 ?
Do you know the equivalent through a command line ?

You say also:
You MUST make this change to the local security policy to ensure ip addresses show up: Change Local Security Policy -> Local Policies -> Audit Policy and turn failure logging on for "audit account logon events" and "audit logon events". From an admin command prompt: auditpol /set /category:"Logon/Logoff" /success:enable /failure:enable

Do we have also to do it if we are focused only on NTLM and RDP brut force attack ?
If yes, then may be we should also do:
auditpol /set /category:"Account Logon" /success:enable /failure:enable

**Comment by jjxtra** [comment]
The ip address does not show up in the event viewer if it is an NTLM attempt. So hackers can go to town and there is no way to block the attempt. NTLM is quite old, so really shouldn't be enabled anyway.

I don't know the command line equivalent, sorry.

I'll add your auditpol line to the readme.
